[package]
name = "wasm-zip-stream-worker"
description = "A stream style zip compressing tool targeting wasm (worker)"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
wasm-bindgen-futures        = { workspace = true }
console_error_panic_hook    = { workspace = true }
flate2                      = { workspace = true }
crc32fast                   = { workspace = true }
wasm-zip-stream             = { path = "../wasm-zip-stream" }

[dependencies.web-sys]
workspace = true
features = [
    "console",
    "File",
    "ReadableStream",
    "ReadableStreamGetReaderOptions",
    "ReadableStreamReaderMode",
    "ReadableStreamByobReader",
    "Performance",
    "MessageEvent"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
